# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      ice:
        enabled: false
        generate_for:
          exclude:
            - test/
          include:
            - test/**/integration/*
            - test/**/integration/**/*
