# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      ice:
        enabled: true
      json_serializable:
        enabled: true
        options:
          explicit_to_json: true
          include_if_null: false
          any_map: true
