# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      ice:
        enabled: true
        options:
          format_output: true
          _dev: true
      json_serializable:
        options:
          explicit_to_json: true
