name: ice_annotation
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  meta: ^1.7.0

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^2.4.0
