include: 
  package:very_good_analysis/analysis_options.2.4.0.yaml


analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.error.dart"
    - "test/fixture/fixtures/*_bld_opt.dart"
  errors:
    unused_element: ignore
