# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      ice:
        enabled: true
        generate_for:
          include:
            - "test/fixture/*.dart"
        options:
          format_output: true
          _dev: true
          # copy_with: anonymous
          # equatable: false
          # to_string: false
          # ignore_getters_as_props: false
          # create_to_json: false
          # create_from_json: false
          # props: false
      json_serializable:
        enabled: true
        generate_for:
          include:
            - "test/fixture/*.dart"

builders:
  ice:
    import: "package:ice/ice.dart"
    builder_factories: ["iceBuilder"]
    build_extensions: { ".dart": ["ice.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before: ["json_serializable"]
