# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      ice:
        enabled: true
        generate_for:
          exclude:
            - test/
          include:
            - test/**/integration/*
            - test/**/integration/**/*

builders:
  ice:
    import: "package:ice/ice.dart"
    builder_factories: ["iceBuilder"]
    build_extensions: { ".dart": ["ice.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before: ["json_serializable"]

  json_serializable:
    import: "package:ice/ice.dart"
    builder_factories: ["iceJsonSerializable"]
    build_extensions: { ".dart": ["json_serializable.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
