name: ice
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  analyzer: ^2.8.0
  build: ^2.2.1
  build_config: ^1.0.0
  change_case: ^1.0.1
  enum_assist_annotation: ^0.1.0+1
  equatable: ^2.0.3
  ice_annotation:
    git:
      url: 'https://github.com/mrgnhnt96/ice'
      path: 'packages/annotation'
  # ice_annotation:
  #   path: ../annotation
  json_annotation: ^4.4.0
  json_serializable: ^6.1.3
  meta: ^1.7.0
  source_gen: ^1.2.1
  source_helper: ^1.3.1
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  enum_assist: ^0.1.0+1
  generator_test:
    git: https://github.com/mrgnhnt96/generator_test
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
