name: ice
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  analyzer: ^3.0.0
  build_config: ^1.0.0
  change_case: ^1.0.1
  equatable: ^2.0.3
  ice_annotation:
    git:
      url: 'https://github.com/mrgnhnt96/ice'
      path: 'packages/annotation'
  # ice_annotation:
  #   path: ../annotation
  meta: ^1.7.0
  source_gen: ^1.2.1
  source_helper: ^1.3.1
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.7
  expect_error_plus:
    git: https://github.com/mrgnhnt96/expect_error_plus
  generator_test:
    git: https://github.com/mrgnhnt96/generator_test
    # path: ../generator_test
  json_annotation: ^4.4.0
  json_serializable: ^6.1.3
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0

dependency_overrides:
  analyzer: ^3.0.0
